Initial
lesha199614/TAF_AQA18_onl pull request #1
Opened 2022-12-04 13:05 UTC by lesha199614

2022-12-06 16:13 UTC, wildpioneer requested changes

2022-12-06 16:13 UTC, wildpioneer commented on src/test/java/tests/Calculator.java
> +    public int divInt(int a, int b) {
Почему названия методов деления различаются?
Повторить перегрузку методов в Java

2022-12-06 16:13 UTC, wildpioneer commented on src/test/java/tests/DivDoubleTest.java
> +    @Test (testName = "Деление нуля на ноль")
Придерживайся единого форматирования во всем проекте:
Меню Code -> Reformat Code

2022-12-06 16:13 UTC, wildpioneer commented on src/test/java/tests/DivDoubleTest.java
> +    }
Не хватает теста Double.Nan

2022-12-07 19:38 UTC, lesha199614 commented on src/test/java/tests/Calculator.java
> +    public int divInt(int a, int b) {
Назвал одинаково

2022-12-07 19:40 UTC, lesha199614 commented on src/test/java/tests/DivDoubleTest.java
> +    @Test (testName = "Деление нуля на ноль")
Отформатировал весь код

2022-12-07 19:42 UTC, lesha199614 commented on src/test/java/tests/DivDoubleTest.java
> +    }
Он есть: DivDoubleTest строки 13-16

 @Test(testName = "Деление нуля на ноль")
    public void divDoubleZero() {
        Assert.assertEquals(calculator.div(0d, 0d), Double.NaN);
    }

2022-12-13 11:17 UTC, wildpioneer requested changes

2022-12-13 11:17 UTC, wildpioneer commented on src/test/java/tests/BaseTest.java
> +    }
Отсутствуют тесты на:
1. dependsOnMethods
2. groups
3. @Parameters
4. priority
5. retryAnalyzer

2022-12-20 13:11 UTC, wildpioneer commented
Проверено

2022-12-20 13:11 UTC, closed without merging