Advanced actions hw
lesha199614/TAF_AQA18_onl pull request #5
Opened 2023-01-08 19:14 UTC by lesha199614

2023-01-09 21:08 UTC, wildpioneer requested changes

2023-01-09 21:08 UTC, wildpioneer commented on src/test/java/tests/HwTests.java
> +        //actions.click(checkbox).build().perform(); //alternative
Не оставляй закоментированные строки в PR

2023-01-09 21:08 UTC, wildpioneer commented on src/test/java/tests/HwTests.java
> +        String filePath = "/Users/aliakseiv/Documents/IdeaTMS/Auto/TAF_AQA18_onl/TAF_AQA18_onl/src/test/resources/playtika.png";
У меня нет такого пути. Да и не понятно зачем эта переменная, если она не используется

2023-01-09 21:08 UTC, wildpioneer commented on src/test/java/tests/HwTests.java
> +        File folderToSave = new File("/Users/aliakseiv/Downloads");
У меня нет такого пути

2023-01-10 11:16 UTC, lesha199614 commented on src/test/java/tests/HwTests.java
> +        //actions.click(checkbox).build().perform(); //alternative
Убрал

2023-01-10 11:17 UTC, lesha199614 commented on src/test/java/tests/HwTests.java
> +        String filePath = "/Users/aliakseiv/Documents/IdeaTMS/Auto/TAF_AQA18_onl/TAF_AQA18_onl/src/test/resources/playtika.png";
Убрал. Оставил только ту переменную, которую использую

2023-01-10 11:21 UTC, lesha199614 commented on src/test/java/tests/HwTests.java
> +        File folderToSave = new File("/Users/aliakseiv/Downloads");
Добавил путь к сохранению в config.properties, метод в ReadProperties. В BrowserFactory добавил автосохранение в эту папку через ReadProperties и в тесте через ReadProperties проверяю появление нового файла

2023-01-16 19:13 UTC, wildpioneer commented on src/test/java/tests/HwTests.java
> +        File folderToSave = new File("/Users/aliakseiv/Downloads");
folderPath=/Users/aliakseiv/Downloads/Test

От того что ты ее вынес в config у меня этот путь, и ни у кого кроме тебя он не появиться

2023-01-16 19:21 UTC, wildpioneer requested changes

2023-01-16 19:21 UTC, wildpioneer commented on src/test/resources/config.properties
> +folderPath=/Users/aliakseiv/Downloads/Test
folderPath=/Users/aliakseiv/Downloads/Test

От того что ты ее вынес в config у меня этот путь, и ни у кого кроме тебя он не появиться

String home = System.getProperty("user.home");
File file = new File(home+"/Downloads/" + fileName + ".txt");

2023-02-28 09:59 UTC, closed without merging