Wrappers hw
lesha199614/TAF_AQA18_onl pull request #6
Opened 2023-01-28 23:39 UTC by lesha199614

2023-01-30 19:13 UTC, wildpioneer requested changes

2023-01-30 19:13 UTC, wildpioneer commented on src/test/java/elements/DropDown.java
> +        if (isDropDownOpen()) {
Лучше наоборот используя логическое Not:
if (!isDropDownOpen()) {
              uiElement.findElement(By.xpath("./div")).click();
         }

2023-01-30 19:13 UTC, wildpioneer commented on src/test/java/elements/Checkbox.java
> +    public void click() {
Этот метод не учитывает - установлен уже флаг или нет. Получается, что ты пытаешься нажать CheckBox не наугад. Основной смысл в том, чтобы был метод setFlag и removeFlag. Которые будут делать именно то, как они называются

2023-01-30 19:26 UTC, lesha199614 commented on src/test/java/elements/DropDown.java
> +        if (isDropDownOpen()) {
Исправил

2023-01-30 19:27 UTC, lesha199614 commented on src/test/java/elements/Checkbox.java
> +    public void click() {
Добавил setFlag и removeFlag. Убрал обычный клик

2023-02-07 15:09 UTC, wildpioneer commented
Проверено

2023-02-07 15:09 UTC, closed without merging